# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-02 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money_inserted', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
