# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-04 02:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.PositiveIntegerField(default=0)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='machine.Machine')),
            ],
        ),
    ]
